# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c86bab2480d975c939f92b5e43232670b615ed555b1713ec337be0dc68785987469971bfc3ea89e2ee5ec74b7b90324ebbf5388b5a174c2dc4dafe50f514f77f

test:
  secret_key_base: b39d44ee1b1dc2232c627f542437afcff39141007e849703cf05f8d340c80ada6e35de782b52405a2e3612b0a6510a82529931155c2134823cbc6c777727fc72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
